customhost = "database-1.cpaqpifxmlhl.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "christineyowsuetyi-employee"
customregion = "us-east-1"
